[package]
name = "langrisser_heroes_for_ab"
version = "0.1.0"
authors = ["Brandon Rioja <34580058+brioja@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
